- name: copy php-fpm.service
  copy:
    src: php-fpm.service
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: 644
- name: php dir
  shell: test -d /usr/local/php
  ignore_errors: True
  register: php_dir
- name: "php install"
  copy:
    src: php-7.3.2.tar.gz
    dest: "/usr/local/src/php-7.3.2.tar.gz"
    owner: root
    group: root
    mode: 0644
- name: "install php"
  shell: cd /usr/local/src/ && tar xf php-7.3.2.tar.gz && cd php-7.3.2 && ./configure --prefix=/usr/local/php --with-config-file-path=/usr/local/php/etc --with-config-file-scan-dir=/usr/local/php/etc/php.d --with-fpm-user=www --with-fpm-group=www --enable-fpm --enable-opcache --disable-fileinfo --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-iconv --with-freetype-dir --with-jpeg-dir --with-png-dir -with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop --enable-exif --enable-sysvsem --enable-inline-optimization --with-curl=/usr/local --enable-mbregex --enable-mbstring --with-gd --with-openssl --with-mhash --enable-pcntl --enable-sockets --with-xmlrpc --enable-intl --with-xsl --with-gettext --enable-zip --enable-soap --disable-debug && make  && make install && cd /usr/local/php/etc/ && cp -a php-fpm.conf.default php-fpm.conf && cd php-fpm.d && cp -a www.conf.default www.conf
  when: php_dir is failed
- name: template php-fpm.conf
  template:
    src: www.conf.j2
    dest: /usr/local/php/etc/php-fpm.d/www.conf
  notify: php-fpm.service
